# Generated by Django 4.2.29 on 2026-04-08 18:22

from django.db import migrations

def delete_old_data(apps, schema_editor):
    User = apps.get_model('core', 'User')
    # Delete all users EXCEPT the admin user
    users_to_delete = User.objects.exclude(username='admin')
    users_to_delete.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_admin_user'),
    ]

    operations = [
        migrations.RunPython(delete_old_data),
    ]
